# Run all 160 experiments — paste into PowerShell
# Takes ~4 min total

# ═══════════════════════════════════════════════════
# BATCH 1 — Multi-seed: HPA baseline (5 seeds × 6 workloads = 30 runs)
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"smooth","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bursty","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bimodal","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"slow_ramp_up","seed":42}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"smooth","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bursty","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bimodal","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"slow_ramp_up","seed":123}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"smooth","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bursty","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bimodal","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"slow_ramp_up","seed":456}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"smooth","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bursty","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bimodal","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"slow_ramp_up","seed":789}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"smooth","seed":1337}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bursty","seed":1337}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"bimodal","seed":1337}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":1337}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":1337}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"slow_ramp_up","seed":1337}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 2 — Multi-seed: MPC+LSTM (5 seeds × 6 workloads = 30 runs)
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"smooth","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bursty","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bimodal","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"slow_ramp_up","seed":42,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"smooth","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bursty","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bimodal","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"slow_ramp_up","seed":123,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"smooth","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bursty","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bimodal","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"slow_ramp_up","seed":456,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"smooth","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bursty","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bimodal","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"slow_ramp_up","seed":789,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"smooth","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bursty","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"bimodal","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"slow_ramp_up","seed":1337,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 3 — Multi-seed: MPC+Prophet (5 seeds × 6 workloads = 30 runs)
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"smooth","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bursty","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bimodal","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"slow_ramp_up","seed":42,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"smooth","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bursty","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bimodal","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"slow_ramp_up","seed":123,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"smooth","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bursty","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bimodal","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"slow_ramp_up","seed":456,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"smooth","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bursty","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bimodal","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"slow_ramp_up","seed":789,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"smooth","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bursty","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"bimodal","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"slow_ramp_up","seed":1337,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 4 — Cold start sensitivity: Prophet × 5 cold_start levels × 2 key workloads
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"cold_start_s":30,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"cold_start_s":30,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"cold_start_s":60,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"cold_start_s":60,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"cold_start_s":120,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"cold_start_s":120,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"cold_start_s":180,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"cold_start_s":180,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"cold_start_s":300,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"cold_start_s":300,"lambda_sla":150,"forecast_margin":1.06}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 5 — Cold start sensitivity: LSTM × 5 levels × 2 workloads
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"cold_start_s":30,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"cold_start_s":30,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"cold_start_s":60,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"cold_start_s":60,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"cold_start_s":120,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"cold_start_s":120,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"cold_start_s":180,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"cold_start_s":180,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"cold_start_s":300,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"cold_start_s":300,"lambda_sla":50,"forecast_margin":1.15}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 6 — Cold start sensitivity: HPA × 5 levels × 2 workloads (baseline)
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42,"cold_start_s":30}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42,"cold_start_s":30}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42,"cold_start_s":60}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42,"cold_start_s":60}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42,"cold_start_s":120}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42,"cold_start_s":120}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42,"cold_start_s":180}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42,"cold_start_s":180}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"diurnal_burst","seed":42,"cold_start_s":300}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"hpa","forecaster":"none","workload":"flash_crowd","seed":42,"cold_start_s":300}' | Select-Object run_id, status, policy, workload

# ═══════════════════════════════════════════════════
# BATCH 7 — ADAPT + FH-OPT A/B tests (5 seeds × 2 workloads × 2 forecasters × 2 FH modes = 40 runs)
# FH-OFF uses static cold_start_steps=0; FH-ON enables dynamic ADAPT-driven horizon.
# ═══════════════════════════════════════════════════
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":42,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":42,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":42,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":42,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload

Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":123,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":123,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":123,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":123,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":123,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":123,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":123,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":123,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload

Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":456,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":456,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":456,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":456,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":456,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":456,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":456,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":456,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload

Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":789,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":789,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":789,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":789,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":789,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":789,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":789,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":789,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload

Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":1337,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"diurnal_burst","seed":1337,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":1337,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"lstm","workload":"flash_crowd","seed":1337,"lambda_sla":50,"forecast_margin":1.15,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":1337,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"diurnal_burst","seed":1337,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":1337,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":false}' | Select-Object run_id, status, policy, workload
Invoke-RestMethod -Method POST -Uri "http://localhost:8000/v1/runs" -ContentType "application/json" -Body '{"policy":"mpc","forecaster":"prophet","workload":"flash_crowd","seed":1337,"lambda_sla":150,"forecast_margin":1.06,"cold_start_steps":0,"use_fh_opt":true}' | Select-Object run_id, status, policy, workload